### ISSUE TITLE
Supported distributions? Ubuntu 14.04.5LTS

### ISSUE THREAD

**Issue by pongraczi** [sriccio/zabbix-alertscripts#1]
Hi,
Thanks for the script, it seems really useful and make skype/sevabot unnecessary :)

Anyway, my zabbix is running on Ubuntu 14.04.5 and I have issue with the script. It drops an exception:

root@zabbixi386:/usr/lib/zabbix/alertscripts# ./notify_pushbullet.py TOKEN  "Subject" "Message"
Traceback (most recent call last):
  File "./notify_pushbullet.py", line 97, in <module>
    pb = pushbullet.Pushbullet(access_token)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/pushbullet.py", line 43, in __init__
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/pushbullet.py", line 381, in refresh
    self._load_devices()
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/pushbullet.py", line 78, in _load_devices
    resp_dict = self._get_data(self.DEVICES_URL)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet/pushbullet.py", line 64, in _get_data
    resp = self._session.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)
requests.exceptions.SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

root@zabbixi386:/usr/lib/zabbix/alertscripts# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

root@zabbixi386:/usr/lib/zabbix/alertscripts# python -V
Python 2.7.6

Do you have hint, where to go? Thanks
István

**Comment by pongraczi** [comment]
Additional information:
I use end-to-end encryption but it seems after I dig deeper, the script is not prepared for encrypted message.

**Comment by pongraczi** [comment]
Ok, end-to-end encryption is a different thing, not related to this issue.
It seems the main problem is, pyopenssl and openssl must be upgraded, but ubuntu 14.04 is too old for this.
Reference: https://github.com/randomchars/pushbullet.py/issues/103

**Comment by pongraczi** [comment]
I am still in the release upgrade process to 16.04, but I can say the following:

- upgrading python solved the problem 
- and nothing to do with end-to-end encryption,

So, ubuntu 14.04 is not supported by python lib, it needs more recent distribution to work.
